# NFS volume override for Docker Compose
# Usage: docker compose -f docker-compose.yml -f docker-compose.nfs.yml up --build -d

services:
  cvat_server:
    build:
      context: .
    environment:
      CSRF_TRUSTED_ORIGINS: "https://cvat.catslandlady.net"

  traefik:
    environment:
      # Trust X-Forwarded-* headers from external Nginx (SSL termination)
      TRAEFIK_ENTRYPOINTS_web_FORWARDEDHEADERS_INSECURE: "true"

  cvat_ui:
    build:
      context: .
      dockerfile: Dockerfile.ui

volumes:
  cvat_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-cvat/data"

  cvat_logs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-cvat/logs"
